### ISSUE TITLE
How to get the SWIG?

### ISSUE THREAD

**Issue by zhuohoudeputao** [kiddos/pykinect2#6]
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindSWIG.cmake:64 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:13 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by zhuohoudeputao** [comment]
OK. Just run
`sudo apt install swig`

**Comment by kiddos** [comment]
Sorry I didn't do a good job bundling all the dependencies and build tools. 
I basically just install them using apt.

I might want to do that.

**Comment by zhuohoudeputao** [comment]
> Sorry I didn't do a good job bundling all the dependencies and build tools.
> I basically just install them using apt.
> 
> I might want to do that.

I think the version of building tools and dependencies is important for building. I'm waiting for that.
